### ISSUE TITLE
WIFI provisioning script - error encountered

### ISSUE THREAD

**Issue by MoDo-git** [ALLTERCO/shelly-script-examples#77]
Received an error running this script on a ShellyPlus2PM:

**this is the log:**
_Uncaught ReferenceError: "self" is not defined
at for (let papk in self.targetCache) {
^
in function "isInCache" called from if (self.isInCache(cSSID) === false) {
^
in function called from system_

Seems like there is an issue here:
https://github.com/ALLTERCO/shelly-script-examples/blame/297358ede3b448d683a90a6c301e2c82dfd02506/wifi-provision.js#L127-L134

The self variable is used, but it is not defined within the function's scope.

**Comment by chrisharrison123** [comment]
hey, did you ever get to the bottom of this, I'm trying to get this working but have run into the same issue.

**Comment by MoDo-git** [comment]
Never ever got it working. Would be awesome feature if working!!

**Comment by taulfsime** [comment]
@MoDo-git @chrisharrison123 Could you please test this updated version of the script: https://github.com/ALLTERCO/shelly-script-examples/blob/fix-wifi-provision-example/wifi-provision.js

**Comment by chrisharrison123** [comment]
Hi,

Iv been testing the updated script and from what iv found, the script now doesn’t seem to get caught by the “self cache” issue anymore, it connects to the target device but then I lose connection to it, presumably as its now connected to the target but the target never appears to get provisioned and then I cant access it until I reset the unit again.
Is there anything that I’m supposed to configure in here before use?

Also as part of this id asked Chris that this script had a function inserting a preset MQTT configuration, the reason is that when a unit is connected to the wifi, it then connects to one of our MQTT brokers where it is reprogrammed via rpc messages.

Look forward to hearing back.

Thanks

Chris


Chris Harrison
Technical Director
03330 341 312   |  07921800745
***@***.***
resicentral.co.uk
